name: Run node
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron: '*/5 * * * *'
env:
  PANTRY_ID: a6932e6e-deba-444d-80a4-790979d72b1f
jobs:
  run_node:
    name: Run node
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run node
        run: node index.js
