name: Run node
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
jobs:
  run_node:
    name: Run node
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          
      - name: Install modules
        run: npm install
          
      - name: Run node
        env:
          PANTRY_ID: ${{ secrets.PANTRY_ID }}
        run: node index.js
